export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED';

export const ASSESSMENT_LIST_RENDER = 'ASSESSMENT_LIST_RENDER';

export const THOUGHT_CHALLANGE_1 = 'THOUGHT_CHALLANGE_1';
export const THOUGHT_CHALLANGE_2 = 'THOUGHT_CHALLANGE_2';
export const THOUGHT_CHALLANGE_3 = 'THOUGHT_CHALLANGE_3';
